sandti_mvc/sandti_mvc/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace sandti_mvc.Models
{
    public class Job
    {
        public int Id { get; set; }
        [Display(Name = "اسم الوظيفة", Description = "اسم الوظيفة")]
        public string JobTitle { get; set; }
        [Display(Name = "وصف الوظيفة", Description = "وصف الوظيفة")]
        [AllowHtml]
        public string JobContent { get; set; }
        [Display(Name = "صورة الوظيفة", Description = "صورة الوظيفة")]
        public string JobImage { get; set; }
        [Display(Name = "فئة الوظيفة", Description = "فئة الوظيفة")]
        public int CategoryID { get; set; }
        public string UserID { get; set; }
        public virtual Category Category { get; set; }
        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<ApplyForJob> ApplyJobs { get; set; }


    }
}

sandti_mvc/sandti_mvc/Models/JobsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sandti_mvc.Models
{
    public class JobsViewModel
    {
        public string JobTitle { get; set; }
        public IEnumerable<ApplyForJob> Items { get; set; }

    }
}

sandti_mvc/sandti_mvc/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using sandti_mvc.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace sandti_mvc.Controllers
{
    //[Authorize(Roles = "Admins")]
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        public ActionResult Index()
        {
            var jobs = db.Jobs.Include(j => j.Category);
            return View(jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "CategoryName");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    job.JobImage = upload.FileName;
                    job.UserID = User.Identity.GetUserId();
                }
                catch
                {
                    job.JobImage = "Sandati Logo.png";
                }
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryID);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryID);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), job.JobImage);
                try
                {
                    if(upload != null)
                    {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    job.JobImage = upload.FileName;
                    }
                }
                catch
                {
                    job.JobImage = "Sandati Logo.png";
                }
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryID);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sandti_mvc/sandti_mvc/Views/Jobs/Create.cshtml
@model sandti_mvc.Models.Job

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Create</h2>
@*https://ckeditor.com/ckeditor-4/download/*@
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Create", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control", placeholder = "السلام عليكم", @id = "JobContent" } })
                @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "فئة الوظيفة", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    CKEDITOR.replace("JobContent");
</script>

sandti_mvc/sandti_mvc/Views/Jobs/Delete.cshtml
@model sandti_mvc.Models.Job

@{
    sandti_mvc.Models.Job job = Model;
    ViewBag.Title = "حذف وظيفة " + job.JobTitle.ToString();
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>هل أنت متأكد من حذف الوظيفة؟</h3>
<div>
    @*<h4>Job</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.JobImage)"
                 class="thumbnail" style="width:48px; height:48px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="تأكيد الحذف" class="btn btn-danger" /> |
            @Html.ActionLink("العودة إلى قائمة الوظائف", "Index")
        </div>
    }
</div>

sandti_mvc/sandti_mvc/Views/Jobs/Details.cshtml
@model sandti_mvc.Models.Job

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.JobContent).ToString()))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.JobImage)" 
                 class="thumbnail" style="width:48px; height:48px;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

sandti_mvc/sandti_mvc/Views/Jobs/Edit.cshtml
@model sandti_mvc.Models.Job

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Jobs", FormMethod.Post, new {enctype= "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <div class="alert alert-danger" id="error-div" style="display:none">
        <span id="view-err"></span>
    </div>

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.JobImage)


    <div class="form-group">
        @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload" id="myImage" />
            @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryID, "فئة الوظيفة", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="حفظ" class="btn btn-default" id="save" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("العودة إلى القائمة", "Index")
</div>

@section scripts{
<script>
    $(function () {
        $("#save").click(function () {
            //هناك مشكلة تكرار الخطأ عند النقر المتكرر

            //Check if the input is Empty
            //if ($("#JobImage").val == "") {
            //    $("#error-div").fadeIn();
            //    $("#view-err").append("رجاءً قم باختيار صورة");
            //    return false;
            //}

            if ($("#myImage").val != "") {
                //Check if the Image Size is valid (2 MB)
                var myFileSize = document.getElementById("myImage").files[0].size / 1024 / 1024;
                if (myFileSize > 2) {
                    $("#error-div").fadeIn();
                    $("#view-err").append("رجاءً قم باختيار صورة حجمها أقل من 2 ميغا بايت");
                    return false;
                }
                //Check if the Image extension is valid
                var filename = document.getElementById("myImage").value;
                var extensionImg = filename.substr(filename.lastIndexOf('.') + 1);
                var vaildExtension = ['jpg', 'png', 'gif', 'bmp'];

                if ($.inArray(extensionImg, vaildExtension) == -1) {
                    $("#error-div").fadeIn();
                    $("#view-err").append("يبدو أنّ الملف المرفق ليس صورة");
                    return false;
                }
            }
        });
    });
</script>
    }

sandti_mvc/sandti_mvc/Views/Jobs/Index.cshtml
@model IEnumerable<sandti_mvc.Models.Job>

@{
    ViewBag.Title = "قائمة الوظائف";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("إضافة وظيفة جديدة", "Create")
</p>
<table class="table table-stripped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobContent)
        </td>
        <td>            
            <img src="~/Uploads/@Html.DisplayFor(modelItem => item.JobImage)"
                 class="thumbnail" style="width:48px; height:48px;" />
        </td>
        <td>
            @Html.ActionLink("تعديل", "Edit", new { id=item.Id }) |
            @Html.ActionLink("تفاصيل", "Details", new { id=item.Id }) |
            @Html.ActionLink("حذف", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>